version: '3.5'

networks:
   jsql-app-net:
       name: jsql-app-net
       #driver: overlay
       driver: bridge

volumes:
   mysql-test-storage:
   cassandra-test-storage:

services:

   mysql-db:
      image: mysql:8.0.13
      environment:
          MYSQL_DATABASE: testDB
          MYSQL_ROOT_PASSWORD: root
      ports:
          - 3306:3306
      networks:
          - jsql-app-net
      volumes:
          - mysql-test-storage:/var/lib/mysql

   cassandra:
         image: cassandra:latest
         ports:
           - 9042:9042
         networks:
           - jsql-app-net
         volumes:
           - cassandra-test-storage:/var/lib/cassandra